[versions]
agp = "8.13.1"
accompanist = "0.36.0"
firebaseAdmin = "9.2.0"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
compose="1.9.3"
activityCompose = "1.11.0"
composeBom = "2025.10.00"
material-icons-core = "1.7.8"
navigationCompose = "2.9.5"
material = "1.13.0"
kotlinxSerialization = "1.6.0"
<<<<<<< HEAD
googleServices = "4.4.4"
firebaseBom = "34.6.0"
=======
cameraCore = "1.5.2"
>>>>>>> PointsBadge

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
firebase-admin = { module = "com.google.firebase.:firebase-admin", version.ref = "firebaseAdmin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "material-icons-core" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons-core" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-compose-animation = {module = "androidx.compose.animation:animation", version.ref="compose"}
accompanist-navigation-animation = {module = "com.google.accompanist:accompanist-navigation-animation", version.ref="accompanist"}
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
kotlinx-serialization-json = {group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
firebase-bom = {group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom"}
firebase-auth = {group = "com.google.firebase", name = "firebase-auth"}
firebase-firestore = {group = "com.google.firebase", name = "firebase-firestore"}
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-services = {id = "com.google.gms.google-services", version.ref = "googleServices"}
compose-compiler = {id = "com.jetbrains.kotlin.plugin.compose", version.ref = "kotlin"}

